services:
  - type: web
    name: imperium-volunteer-leaderboard
    env: python
    region: oregon  # or use your preferred Render region
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    plan: free
